model:
  # out_channels, kernel_size, stride, res_depth, groups, depth 
  net:
    0: [64, 3, 1, 1, 1, 1]
    1: [128, 3, 1, 1, 1, 1]
    2: [256, 3, 1, 1, 1, 1]
  mlp: [1024, 512]
  max_pool_stride: 2
  residual: True
