model:
  # out_channels, kernel_size, stride, res_depth, groups, depth 
  net:
    0: [64, 3, 1, 3, 8, 5]
    1: [128, 3, 1, 3, 8, 4]
    2: [256, 3, 1, 3, 8, 3]
    3: [512, 3, 1, 3, 8, 2]
  mlp: []
  max_pool_stride: 2
  residual: True
